/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125BlogIndexRouteImport } from './routes/{-$locale}/blog/index'
import { Route as Char123LocaleChar125BlogSaelgBilHoejestePrisRouteImport } from './routes/{-$locale}/blog/saelg-bil-hoejeste-pris'
import { Route as Char123LocaleChar125BlogHvadErMinBilVaerdRouteImport } from './routes/{-$locale}/blog/hvad-er-min-bil-vaerd'
import { Route as Char123LocaleChar125BlogBilVurderingGuideRouteImport } from './routes/{-$locale}/blog/bil-vurdering-guide'
import { Route as Char123LocaleChar125AuthSignupRouteImport } from './routes/{-$locale}/auth/signup'
import { Route as Char123LocaleChar125AuthLoginRouteImport } from './routes/{-$locale}/auth/login'
import { Route as Char123LocaleChar125AuthAdminRouteImport } from './routes/{-$locale}/auth/admin'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BlogIndexRoute =
  Char123LocaleChar125BlogIndexRouteImport.update({
    id: '/{-$locale}/blog/',
    path: '/{-$locale}/blog/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BlogSaelgBilHoejestePrisRoute =
  Char123LocaleChar125BlogSaelgBilHoejestePrisRouteImport.update({
    id: '/{-$locale}/blog/saelg-bil-hoejeste-pris',
    path: '/{-$locale}/blog/saelg-bil-hoejeste-pris',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BlogHvadErMinBilVaerdRoute =
  Char123LocaleChar125BlogHvadErMinBilVaerdRouteImport.update({
    id: '/{-$locale}/blog/hvad-er-min-bil-vaerd',
    path: '/{-$locale}/blog/hvad-er-min-bil-vaerd',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125BlogBilVurderingGuideRoute =
  Char123LocaleChar125BlogBilVurderingGuideRouteImport.update({
    id: '/{-$locale}/blog/bil-vurdering-guide',
    path: '/{-$locale}/blog/bil-vurdering-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthSignupRoute =
  Char123LocaleChar125AuthSignupRouteImport.update({
    id: '/{-$locale}/auth/signup',
    path: '/{-$locale}/auth/signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthLoginRoute =
  Char123LocaleChar125AuthLoginRouteImport.update({
    id: '/{-$locale}/auth/login',
    path: '/{-$locale}/auth/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AuthAdminRoute =
  Char123LocaleChar125AuthAdminRouteImport.update({
    id: '/{-$locale}/auth/admin',
    path: '/{-$locale}/auth/admin',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/admin': typeof Char123LocaleChar125AuthAdminRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/auth/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/blog/bil-vurdering-guide': typeof Char123LocaleChar125BlogBilVurderingGuideRoute
  '/{-$locale}/blog/hvad-er-min-bil-vaerd': typeof Char123LocaleChar125BlogHvadErMinBilVaerdRoute
  '/{-$locale}/blog/saelg-bil-hoejeste-pris': typeof Char123LocaleChar125BlogSaelgBilHoejestePrisRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/admin': typeof Char123LocaleChar125AuthAdminRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/auth/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/blog/bil-vurdering-guide': typeof Char123LocaleChar125BlogBilVurderingGuideRoute
  '/{-$locale}/blog/hvad-er-min-bil-vaerd': typeof Char123LocaleChar125BlogHvadErMinBilVaerdRoute
  '/{-$locale}/blog/saelg-bil-hoejeste-pris': typeof Char123LocaleChar125BlogSaelgBilHoejestePrisRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/auth/admin': typeof Char123LocaleChar125AuthAdminRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125AuthLoginRoute
  '/{-$locale}/auth/signup': typeof Char123LocaleChar125AuthSignupRoute
  '/{-$locale}/blog/bil-vurdering-guide': typeof Char123LocaleChar125BlogBilVurderingGuideRoute
  '/{-$locale}/blog/hvad-er-min-bil-vaerd': typeof Char123LocaleChar125BlogHvadErMinBilVaerdRoute
  '/{-$locale}/blog/saelg-bil-hoejeste-pris': typeof Char123LocaleChar125BlogSaelgBilHoejestePrisRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}/'
    | '/{-$locale}/auth/admin'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/signup'
    | '/{-$locale}/blog/bil-vurdering-guide'
    | '/{-$locale}/blog/hvad-er-min-bil-vaerd'
    | '/{-$locale}/blog/saelg-bil-hoejeste-pris'
    | '/{-$locale}/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/{-$locale}/auth/admin'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/signup'
    | '/{-$locale}/blog/bil-vurdering-guide'
    | '/{-$locale}/blog/hvad-er-min-bil-vaerd'
    | '/{-$locale}/blog/saelg-bil-hoejeste-pris'
    | '/{-$locale}/blog'
  id:
    | '__root__'
    | '/{-$locale}/'
    | '/{-$locale}/auth/admin'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/signup'
    | '/{-$locale}/blog/bil-vurdering-guide'
    | '/{-$locale}/blog/hvad-er-min-bil-vaerd'
    | '/{-$locale}/blog/saelg-bil-hoejeste-pris'
    | '/{-$locale}/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125AuthAdminRoute: typeof Char123LocaleChar125AuthAdminRoute
  Char123LocaleChar125AuthLoginRoute: typeof Char123LocaleChar125AuthLoginRoute
  Char123LocaleChar125AuthSignupRoute: typeof Char123LocaleChar125AuthSignupRoute
  Char123LocaleChar125BlogBilVurderingGuideRoute: typeof Char123LocaleChar125BlogBilVurderingGuideRoute
  Char123LocaleChar125BlogHvadErMinBilVaerdRoute: typeof Char123LocaleChar125BlogHvadErMinBilVaerdRoute
  Char123LocaleChar125BlogSaelgBilHoejestePrisRoute: typeof Char123LocaleChar125BlogSaelgBilHoejestePrisRoute
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/blog/': {
      id: '/{-$locale}/blog/'
      path: '/{-$locale}/blog'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/blog/saelg-bil-hoejeste-pris': {
      id: '/{-$locale}/blog/saelg-bil-hoejeste-pris'
      path: '/{-$locale}/blog/saelg-bil-hoejeste-pris'
      fullPath: '/{-$locale}/blog/saelg-bil-hoejeste-pris'
      preLoaderRoute: typeof Char123LocaleChar125BlogSaelgBilHoejestePrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/blog/hvad-er-min-bil-vaerd': {
      id: '/{-$locale}/blog/hvad-er-min-bil-vaerd'
      path: '/{-$locale}/blog/hvad-er-min-bil-vaerd'
      fullPath: '/{-$locale}/blog/hvad-er-min-bil-vaerd'
      preLoaderRoute: typeof Char123LocaleChar125BlogHvadErMinBilVaerdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/blog/bil-vurdering-guide': {
      id: '/{-$locale}/blog/bil-vurdering-guide'
      path: '/{-$locale}/blog/bil-vurdering-guide'
      fullPath: '/{-$locale}/blog/bil-vurdering-guide'
      preLoaderRoute: typeof Char123LocaleChar125BlogBilVurderingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth/signup': {
      id: '/{-$locale}/auth/signup'
      path: '/{-$locale}/auth/signup'
      fullPath: '/{-$locale}/auth/signup'
      preLoaderRoute: typeof Char123LocaleChar125AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth/login': {
      id: '/{-$locale}/auth/login'
      path: '/{-$locale}/auth/login'
      fullPath: '/{-$locale}/auth/login'
      preLoaderRoute: typeof Char123LocaleChar125AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/auth/admin': {
      id: '/{-$locale}/auth/admin'
      path: '/{-$locale}/auth/admin'
      fullPath: '/{-$locale}/auth/admin'
      preLoaderRoute: typeof Char123LocaleChar125AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125AuthAdminRoute: Char123LocaleChar125AuthAdminRoute,
  Char123LocaleChar125AuthLoginRoute: Char123LocaleChar125AuthLoginRoute,
  Char123LocaleChar125AuthSignupRoute: Char123LocaleChar125AuthSignupRoute,
  Char123LocaleChar125BlogBilVurderingGuideRoute:
    Char123LocaleChar125BlogBilVurderingGuideRoute,
  Char123LocaleChar125BlogHvadErMinBilVaerdRoute:
    Char123LocaleChar125BlogHvadErMinBilVaerdRoute,
  Char123LocaleChar125BlogSaelgBilHoejestePrisRoute:
    Char123LocaleChar125BlogSaelgBilHoejestePrisRoute,
  Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
